### ISSUE TITLE
使用0.4.1出现的问题

### ISSUE THREAD

**Issue by QC-L** [ctripcorp/moles-packer#28]
![image](https://cloud.githubusercontent.com/assets/13861040/20969154/bde69504-bcc2-11e6-9012-867d58e0a6ef.png)

错误提示如下:
[MOLES_PACKER] -- options parsed --

  name            value                                          
  --------------  -----------------------------------------------
  base            "/Users/xxx/ReactNative/v031"         
  bundle          true                        
  commonOutput    "BASE/build/moles.common"   
  dev             false                       
  entry           "BASE/index.ios.js"         
  execOnRequired  false                       
  input           "BASE/"                     
  isCLI           true                        
  metaOutput      "BASE/build/moles.meta.json"
  minify          false                       
  output          "BASE/build"                
  platform        "ios"                                 
  single          false                       
  standalone      true                        
  verbose         true                        

[MOLES_PACKER] -- Process common bundle --
module.js:474
    throw err;
    ^

Error: Cannot find module 'node-haste/lib/DependencyGraph/docblock.js'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at _create_common (/usr/local/lib/node_modules/moles-packer/lib/packCommon.js:37:17)
    at _ME (/usr/local/lib/node_modules/moles-packer/lib/packCommon.js:282:18)
    at _ME (/usr/local/lib/node_modules/moles-packer/lib/pack.js:22:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/moles-packer/bin/pack.js:4:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)

**Comment by QC-L** [comment]
执行 npm install -g node-haste ，可以解决如上问题

**Comment by QC-L** [comment]
上面的问题解决后，又出现了如下问题
![image](https://cloud.githubusercontent.com/assets/13861040/20970129/00e2d29c-bcc7-11e6-8b74-f92f0b5a41ec.png)
[MOLES_PACKER] Common modules ready.
[MOLES_PACKER] -- Process business code --
[SOURCE] index.ios.js ( entry )
start ... react / es2015 ... /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176
          throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
          ^

ReferenceError: Unknown plugin "transform-es5-property-mutators" specified in "base" at 0, attempted to resolve relative to "/Users/QCL/ReactNative/v031"
    at /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:154:20)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:36)
    at OptionManager.init (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _transform_react (/usr/local/lib/node_modules/moles-packer/lib/transform.js:137:24)
    at _one (/usr/local/lib/node_modules/moles-packer/lib/transform.js:110:9)

**Comment by QC-L** [comment]
上述错误 执行 npm install babel-plugin-transform-es5-property-mutators@6.8.0
安装下插件

**Comment by QC-L** [comment]
解决了上面的错误，还会遇到如下错误
![image](https://cloud.githubusercontent.com/assets/13861040/20994348/d123383a-bd2a-11e6-9077-e4fd7dc7a60d.png)

[MOLES_PACKER] -- Process business code --
[SOURCE] index.ios.js ( entry )
start ... react / es2015 ... /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

Error: Couldn't find preset "es2015" relative to directory "/Users/QCL/ReactNative/v031"
    at /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _transform_react (/usr/local/lib/node_modules/moles-packer/lib/transform.js:137:24)

**Comment by QC-L** [comment]
执行如下代码 
npm install --save-dev babel-preset-es2015
解决上述错误

**Comment by QC-L** [comment]
上述错误解决后，出现最后一个问题
![image](https://cloud.githubusercontent.com/assets/13861040/20994400/16f97356-bd2b-11e6-8c59-66ae620f3e9a.png)
[MOLES_PACKER] -- Process business code --
[SOURCE] index.ios.js ( entry )
start ... react / es2015 ... /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

Error: Couldn't find preset "stage-0" relative to directory "/Users/QCL/ReactNative/v031"
    at /usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/usr/local/lib/node_modules/moles-packer/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at _transform_react (/usr/local/lib/node_modules/moles-packer/lib/transform.js:137:24)

**Comment by QC-L** [comment]
执行
npm install --save-dev babel-preset-stage-0
再进行分包，大功告成

**Comment by hehex9** [comment]
这也太坑了
